//root/komponenten/Layout.jsx
/**
 * Layout-Komponente fuer wiederverwendbaren Seitenrahmen, kombiniert Kopfbereich, Inhaltscontainer und optionale Fusszeile.
 * Kompositionsmuster mit children-Prop, Import von Unterkomponenten und optional next/head fuer Meta-Tags im Pages Router.
 * Input Child-Content aus aufrufenden Seiten, Logic strukturelle Einbettung, Output konsistente UI-Huelle ueber mehrere Routen.
 * Next.js Besonderheit Layout-Ketten variieren zwischen Pages Wrappern und App-Router Root-Layouts, hier projektintern abstrahiert.
 */

import Head from 'next/head';
import Navigation from '../komponenten/Navigation';
import Fusszeile from '../komponenten/Fusszeile';

export default function Layout( {children} ) {
    return (
        <div>

            <Head>
                <title>Liefermax - Dein Lieferservice</title>
                <meta name="description" content="Generated by udemy"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navigation />
              <div className="container">
                {children}
              </div>
            <Fusszeile />

        </div>);
}
